server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/EnesHidayet/ConfigServer.git"
          default-label: "main"
          skip-ssl-validation: true
          username: "EnesHidayet"
          password: ${GIT_KEY} # bu bilgiyi git işletim sisteminin environment veriable dan al.