apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-postgresql
spec:
  selector: # Deployment objesi pod ları yakalabilmek için eşleşme arıyor.
    matchLabels:
      db: pod-deployment-postgresql
  template: #Buradan itibaren pod ile alakalı özellikleri yazıyoruz.
    metadata:
      labels: # Bir pod un etiketi.
        db: pod-deployment-postgresql
    spec:
      containers:
      - name: pod-postgresql # pod un adı
        image: postgres # hub.docker üzerindeki image adı (mongo, redis, elasticsearch...)
        resources:
          limits:
            memory: "128Mi" # node ın total ram inden ne kadar kullanılacağını belirtiyoruz.
            cpu: "200m" # node vCpu su 2 ise bu -> 2000M demektir.
        ports:
        - containerPort: 5432
        env: # işletim sistemine eklemek istedğiniz environmentvariable listesine ekliyoruz.
          - name: POSTGRES_PASSWORD
            value: root